services:
  database:
    image: mysql
    ports:
      - 3306:3306
    volumes:
      - ./database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always
  app:
    image: node
    ports:
      - 3000:3000
    volumes:
      - .:/app
    tty: true
